policies:
  - name: terraform
    rules: |-
      path "auth/*" {
        capabilities = ["create", "read", "update", "delete", "list", "sudo"]
      }

      # Create, update, and delete auth methods
      path "sys/auth/*" {
        capabilities = ["create", "update", "delete", "sudo"]
      }

      # List auth methods
      path "sys/auth" {
        capabilities = ["read"]
      }

      # List existing policies
      path "sys/policies/acl" {
        capabilities = ["list"]
      }

      # Create and manage ACL policies
      path "sys/policies/acl/*" {
        capabilities = ["create", "read", "update", "delete", "list", "sudo"]
      }

      # Manage secrets engines
      path "sys/mounts/*" {
        capabilities = ["create", "read", "update", "delete", "list", "sudo"]
      }

      # List existing secrets engines.
      path "sys/mounts" {
        capabilities = ["read"]
      }

      # Manage audit devices
      path "sys/audit/*" {
        capabilities = ["create", "read", "update", "delete", "list", "sudo"]
      }

      # List existing audit devices
      path "sys/audit" {
        capabilities = ["read"]
      }

auth:
  - type: aws
    # Make the auth provider visible in the web ui
    # See https://www.vaultproject.io/api/system/auth.html#config for more
    # information.
    options:
      listing_visibility: "unauth"
    config:
      {}
      # iam_server_id_header_value: vault-dev.example.com # consider setting this to the Vault server's DNS name
    roles:
      - name: gitlab-runner-vault
        auth_type: ec2
        bound_iam_role_arn: arn:aws:iam::843222783279:role/gitlab-runner-vault
        policies: terraform
        period: 1h
